### ISSUE TITLE
Shorten names (master issue)

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker#339]
This is about shortening the sometimes over-long full names of classes. Note that this impacts on a lot of repositories, but that the visible functionality changes should be minimal to none.

Generic Layer
---
- [x] https://github.com/SpiNNakerManchester/SpiNNMachine/pull/41
- [x] https://github.com/SpiNNakerManchester/SpiNNMan/pull/82
- [x] https://github.com/SpiNNakerManchester/PACMAN/pull/99
- [x] https://github.com/SpiNNakerManchester/SpiNNStorageHandlers/pull/9
- [x] https://github.com/SpiNNakerManchester/DataSpecification/pull/23
- [x] https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/153
- [x] https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/50
- [x] https://github.com/SpiNNakerManchester/sPyNNaker/pull/338
- [x] https://github.com/SpiNNakerManchester/sPyNNakerExternalDevicesPlugin/pull/62
- [x] https://github.com/SpiNNakerManchester/sPyNNakerExtraModelsPlugin/pull/26

sPyNNaker 7
---
- [x] https://github.com/SpiNNakerManchester/sPyNNaker7/pull/12
- [x] https://github.com/SpiNNakerManchester/sPyNNaker7ExternalDevicesPlugin/pull/6
- [x] https://github.com/SpiNNakerManchester/sPyNNaker7ExtraModelsPlugin/pull/1
- [x] https://github.com/SpiNNakerManchester/sPyNNaker7NewModelTemplate/pull/2

sPyNNaker 8
---
- [x] https://github.com/SpiNNakerManchester/sPyNNaker8/pull/26
- [x] https://github.com/SpiNNakerManchester/sPyNNaker8ExternalDevicesPlugin/pull/6
- [x] https://github.com/SpiNNakerManchester/sPyNNaker8ExtraModelsPlugin/pull/2
- [x] https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/2

**Comment by dkfellows** [comment]
NB: some of the above commits increase the amount of testing.

**Comment by rowleya** [comment]
Merged
